url: https://FlightEye.github.io
baseurl: 

# Site settings
title: FlightEye
email: burnettcj1966@gwu.edu
description: "FlightEye is a revolutionary new product that will change the way pilots view safety."


# Team names, titles and social links
peopleTop:
- name: Jett Jacobs
  pic: 1
  position: Unity/XR Lead
  social:
    - title: linkedin
      url: https://www.linkedin.com/feed/update/urn:li:activity:6979252947675181056/
    - title: github
      url: https://github.com/jettjacobs

- name: Noah Chinitz
  pic: 2
  position: Hardware/Linux Lead
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/noah-chinitz-024032142/
    - title: github
      url: https://github.com/NoahChinitzGWU

peopleBottom:
- name: Aaron Hill
  pic: 3
  position: Research Lead
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/aaron-hill-466228198/
    - title: github
      url: https://github.com/aaronmhill01

- name: Connor Burnett
  pic: 4
  position: Software Engineering Lead
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/connor-burnett-754225198/
    - title: github
      url: https://github.com/burnettcj1966


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty